apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-internal-creds-secrets
  namespace: ${ARGOCD_ENV_INGRESS_NAMESPACE}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-cluster-secret-store
  target:
    name: oauth-internal-creds-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: oauth-internal-creds-secrets
