# Chicken and eggs problem: https://cert-manager.io/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl/#8-re-configure-the-ingress-for-ssl

apiVersion: v1
kind: Secret
metadata:
  name: ${ARGOCD_ENV_INGRESS_NAME}-cert
  namespace: ${ARGOCD_ENV_INGRESS_NAMESPACE}
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""